version:  "3"

services:
  db:
    image: mysql:5.7
    container_name: docker_rails_db
    volumes:
      - db_store:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  app:
    build: .
    container_name: docker_rails_app
    volumes:
      - .:/myapp
    depends_on:
      - db
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  db_store: